### ISSUE TITLE
display of register arrays

### ISSUE THREAD

**Issue by ekallal** [SystemRDL/PeakRDL-Markdown#5]
The top-level address map displays the array size for each occurrence of a register defined in an array.  I think the intent is to display the instance number.  Happy to provide additional details.

Current output: 

|Offset|       Identifier      |                 Name                 |
|------|-----------------------|--------------------------------------|
| 0x104|  TEST_REGISTER[8]     |       Test Register description      |
| 0x108|  TEST_REGISTER[8]     |       Test Register description      |
| 0x10C|  TEST_REGISTER[8]     |       Test Register description      |
| 0x110|  TEST_REGISTER[8]     |       Test Register description      |
| 0x114|  TEST_REGISTER[8]     |       Test Register description      |
| 0x118|  TEST_REGISTER[8]     |       Test Register description      |
| 0x11C|  TEST_REGISTER[8]     |       Test Register description      |
| 0x120|  TEST_REGISTER[8]     |       Test Register description      |

Expected output: 

|Offset|       Identifier      |                 Name                 |
|------|-----------------------|--------------------------------------|
| 0x104|  TEST_REGISTER[0]     |       Test Register description      |
| 0x108|  TEST_REGISTER[1]     |       Test Register description      |
| 0x10C|  TEST_REGISTER[2]     |       Test Register description      |
| 0x110|  TEST_REGISTER[3]     |       Test Register description      |
| 0x114|  TEST_REGISTER[4]     |       Test Register description      |
| 0x118|  TEST_REGISTER[5]     |       Test Register description      |
| 0x11C|  TEST_REGISTER[6]     |       Test Register description      |
| 0x120|  TEST_REGISTER[7]     |       Test Register description      |

**Comment by ekallal** [comment]
The incorrect array index comes from here.  Perhaps replace with 

`name = self._node_name_sanitized(node.get_path_segment())`

https://github.com/SystemRDL/PeakRDL-Markdown/blob/ed0796327aef25efc986a32beb77f38807acc967/src/peakrdl_markdown/exporter.py#L122C57-L123C47 

        identifier = node.inst_name
        if node.is_array:
            assert node.array_dimensions is not None
            identifier += "".join(f"[{dim}]" for dim in node.array_dimensions)
        name = self._node_name_sanitized(node)

**Comment by MarekPikula** [comment]
Ah, good catch. I could look into it next week. If you have a ready fix, please don't hesitate to push a PR.

**Comment by jeras** [comment]
A related issue here is the duplication of the documentation for each array element.
I think the structure of the documentation should be the same for all generators (HTML, PDF, Markdown), but I have to run a few examples before I can make a proposal.
This month I also discussed with Alex how parameterized definitions are used by generators, and this adds a few extra consideration on how to document everything and just once.

**Comment by jeras** [comment]
Another option for the expected output would be to show the array explicitly instead of each individual element:

| Offset | Identifier | Name |
|----------|----------------|----------|
| `0x104` | `TEST_REGISTER[0:63]` | Test Register description |

Another problem is, that each element of the array has its own documentation section, with the heading lacking any index, just `TEST_REGISTER`.

There is also a conceptual problem. Since a full list of individual array elements adds clutter and causes scrolling fatigue, I would usually prefer a more compact approach, where arrays are represented with a range instead of individual elements, and for each array a single element is documented (if I have 8 identical SPI controllers, I do not need 8 copies of their full description).

On the other hand, if I am looking for the absolute address of a register, than a full listing would be appreciated.

One solution to this problem I see (which is also common in existing documentation), would be to have 2 generators:
- one for a flat table which includes all absolute addresses, but only short names as description,
- the other hierarchical (address offsets), with arrays defined only with a range, and not a list, containing full documentation strings, but only once for each array element.

**Comment by MarekPikula** [comment]
Hi all, please check out the solution from #19, which is released as 1.0.2. I think it solves the original issue from @ekallal, but not necessarily the remark from @jeras. If that's the case, let's close this issue and open a separate one discussing documentation duplication.

**Comment by ekallal** [comment]
this is great.  The summary table at the beginning is most important.  Note that the individual register descriptions still don't contain an array index.  Ideally, they would. 

(Although it's doubtful many look too closely at those since they contents are the same for each instance.)

In the example, line 232 should be "fifo_port[0]", line 280 should be "fifo_port[1]", etc. 

https://github.com/SystemRDL/PeakRDL-Markdown/blob/b9059543eebafd1bc6d09a3270a3afba9f46d703/example/accelera_generic_example.md?plain=1#L232
https://github.com/SystemRDL/PeakRDL-Markdown/blob/b9059543eebafd1bc6d09a3270a3afba9f46d703/example/accelera_generic_example.md?plain=1#L280
